export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_SEARCH_LOCATION = 'UPDATE_SEARCH_LOCATION';
export const UPDATE_CURRENT_WEATHER = 'UPDATE_CURRENT_WEATHER';
export const UPDATE_TEMPERATURE_FORECAST = 'UPDATE_TEMPERATURE_FORECAST';
